fix source VM deletion after migration (#386)
* fix source VM deletion after migration
* detach deleted VM after live migration before deleting
* fix source cores dataset deletion; improve backward compatibility
* improve esmigrate backward compatibility
* fix esmigrate emerg rollback core DS creation
* updated changelog

diff --git a/bin/esmigrate b/bin/esmigrate
--- a/bin/esmigrate
+++ b/bin/esmigrate
@@ -487,7 +487,7 @@ create_core_dataset_err() {
 	# shellcheck disable=SC2155
 	local core_ds="$(_get_core_dataset "${DS_ROOT%% *}")"
 
-	if zfs_dataset_exists "${core_ds}"; then
+	if _zfs_dataset_exists "${core_ds}"; then
 		VM_CORES_RM=""
 		techo "Source VM's cores dataset exists: ${core_ds}"
 	else
@@ -1297,7 +1297,8 @@ _delete_vm() {
 		_vm_remove_indestructible_property "${uuid}" &>/dev/null
 	fi
 
-	_vm_destroy "${uuid}" > /dev/null
+	# we cannot use "vmadm destroy" because it refuses to destroy a detached VM
+	_zone_delete "${uuid}" > /dev/null
 
 	# shellcheck disable=SC2181
 	if [[ $? -eq 0 ]]; then
@@ -1314,26 +1315,39 @@ destroy_datasets_src() {
 	local ds_root
 	local ds_data
 
-	if [[ -z "${DEST_HOST}" ]]; then  # local migration -> remove only migrated source datasets
-		if [[ -n "${DS_ROOT}" ]]; then
-			ds_root=${DS_ROOT%% *}
-			_destroy_dataset "${ds_root}"
+	if live_migration && [[ -n "${DEST_HOST}" ]]; then
+		# we need to get src VM to detached state before datasets removal
+		# (apply delete only to remote migration)
+		techo "Halting source VM"
+		_zone_halt "${UUID_SRC}"
+
+		# core dataset can be destroyed only after VM stop
+		set_vm_status_src
+		destroy_core_dataset
+
+		techo "Detaching source VM"
+		_zone_detach "${UUID_SRC}"
+	fi
+
+	# remove migrated source datasets
+	if [[ -n "${DS_ROOT}" ]]; then
+		ds_root=${DS_ROOT%% *}
+		_destroy_dataset "${ds_root}"
+		if [[ -z "${DEST_HOST}" ]]; then  # local migration
 			# Destroy source cores dataset in local migration and when root pool has changed
 			_destroy_dataset "$(_get_core_dataset "${ds_root}")"
 		fi
+	fi
 
-		# The OS zone delegated dataset is a child and destroyed together with the DS_ROOT
-		if [[ "${#DS_DATA[@]}" -ne 0 ]] && is_kvm; then
-			for ds_data in "${DS_DATA[@]}"; do
-				_destroy_dataset "${ds_data%% *}"
-			done
-		fi
+	# The OS zone delegated dataset is a child and destroyed together with the DS_ROOT
+	if [[ "${#DS_DATA[@]}" -ne 0 ]] && is_kvm; then
+		for ds_data in "${DS_DATA[@]}"; do
+			_destroy_dataset "${ds_data%% *}"
+		done
+	fi
 
-	else  # remote migration -> remove source VM, which will remove all source datasets
+	if [[ -n "${DEST_HOST}" ]]; then  # remote migration -> remove also source VM
 		_delete_vm "${UUID_SRC}"
-		if [[ -z "${VM_DETACHED_FAKE}" ]]; then
-			_destroy_dataset "${DS_ROOT%% *}"  # We have to destroy the root zone manually, because vmadm won't do it for detached zone
-		fi
 	fi
 
 	DS_RECV=()
@@ -1342,10 +1356,20 @@ destroy_datasets_src() {
 }
 
 vminfod_restart() {
-	if _dest_host_cmd _vminfod_restart; then
-		techo "Restarted vminfod"
+	local service_name=""
+
+	# check compatibility with older esmigrate clients
+	if remote_function_exists _vminfod_restart; then
+		service_name="vminfod"
 	else
-		echo "vminfod restart failed" 1>&2
+		techo "Info: the remote side has v3.0.0 or older"
+		service_name="vmadmd"
+	fi
+
+	if _dest_host_cmd "_${service_name}_restart"; then
+		techo "Restarted ${service_name}"
+	else
+		echo "${service_name} restart failed" 1>&2
 	fi
 }
 
@@ -1353,10 +1377,17 @@ wait_for_vmadm_detect() {
 	local timeout=180	# sec
 
 	techo "Waiting for VM to become visible by vmadm"
-	if _dest_host_cmd _vm_wait_for_become_visble "${UUID_SRC}" "${timeout}"; then
-		techo "VM is present"
+
+	# check compatibility with older esmigrate clients
+	if remote_function_exists _vm_wait_for_become_visble; then
+		if _dest_host_cmd _vm_wait_for_become_visble "${UUID_SRC}" "${timeout}"; then
+			techo "VM is present"
+		else
+			die ${ERR_VM_AFTER_CHECK} "Transferred VM was not detected by vminfod!"
+		fi
 	else
-		die ${ERR_VM_AFTER_CHECK} "Transferred VM was not detected by vminfod!"
+		# older clients must just wait
+		sleep 10
 	fi
 }
 
